### ISSUE TITLE
Wireframe MVP

### ISSUE THREAD

**Issue by ap2322** [Tweet-311-Denver/tweet_311_denver_ui#2]
Form -> Confirm Tweet & Confirm 311 form -> success with new form

**Comment by Garrett-Iannuzzi** [comment]
<img width="282" alt="Screen Shot 2020-02-15 at 2 40 35 PM" src="https://user-images.githubusercontent.com/48968224/74595623-22f6a400-5001-11ea-8ed4-dc00a1fe5578.png">

**Comment by Garrett-Iannuzzi** [comment]
<img width="275" alt="Screen Shot 2020-02-15 at 3 05 30 PM" src="https://user-images.githubusercontent.com/48968224/74595896-9e0d8980-5004-11ea-846b-9316edd2d987.png">

**Comment by Garrett-Iannuzzi** [comment]
<img width="275" alt="Screen Shot 2020-02-15 at 3 10 43 PM" src="https://user-images.githubusercontent.com/48968224/74595946-59362280-5005-11ea-900b-4cf6646dda13.png">
